#!/usr/bin/env bash

export DEBUG_LOGGING="true"
export STT_SERVICE="vosk"
export STT_LANGUAGE="en-US"
export USE_INBUILT_BLE="false"
export KNOWLEDGE_ENABLED="false"
export WEATHERAPI_ENABLED="false"
export VOSK_THERMAL_MANAGEMENT="true"
export VOSK_WITH_GRAMMER="false"
export DISABLE_MDNS="false"
export NO8084="false"
export JDOCS_PINGER_ENABLED="true"
export SDK_ENABLED="true"
export PORT80_ENABLED="true"
